import streamlit as st


r"""
# Конвертация сеток в формат DOLPHIN XML

Утилита dolfin-convert предоставляет возможность конвертации сетки в необходимый формат.

Использование:

```
dolfin-convert input.x output.y
```

- x - исходное расширение файла (исходный формат сетки).
- y - целевое расширение файла (целевой формат сетки).
"""

with st.expander("Пример использования"):
    """
    ```
    dolfin-convert mesh_example.msh mesh_example.xml
    ```
    """

"""
## Поддерживаемые форматы

  - xml      - DOLFIN XML mesh format (current)
  - xml-old  - DOLFIN XML mesh format (DOLFIN 0.6.2 and earlier)
  - mesh     - Medit, generated by tetgen with option -g
  - Triangle - Triangle file format (input prefix of .ele and .node files)
  - gmsh     - Gmsh, version 2.0 file format
  - metis    - Metis graph file format
  - scotch   - Scotch graph file format
  - diffpack - Diffpack tetrahedral grid format
  - abaqus   - Abaqus tetrahedral grid format
  - ExodusII - Sandia Format (requires ncdump utility from NetCDF)
  - Star-CD  - Star-CD tetrahedral grid format
  
### Расширения и форматы
  - .xml  - xml
  - .mesh - mesh
  - .gmsh - gmsh
  - .msh  - gmsh
  - .gra  - metis
  - .grf  - scotch
  - .grid - diffpack
  - .inp  - abaqus
  - .e	- Exodus II
  - .exo  - Exodus II
  - .ncdf - ncdump'ed Exodus II
  - .vrt and .cell  - starcd
"""


